name: Ferret Submission
description: Submit a ferret
title: "[Submission]: "
labels: ["submission"]
assignees:
  - LeoDog896
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Do always remember that if you're submitting an internet photo, **the photo must be under a creative commons license OR in the public domain**.
  - type: input
    id: image-source
    attributes:
      label: Ferret Image Source
      description: Enter the source URL of the image.
      placeholder: Enter Source URL
  - type: input
    id: image
    attributes:
      label: Ferret Image
      description: Enter the URL of the image. (No image drop-in yet, sadly)
      placeholder: Enter Image URL
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Ferret's Given Name (by Author)
      description: If you don't mind, provide the name of the ferret
      placeholder: Name
  - type: dropdown
    id: sex
    attributes:
      label: Ferret's Sex
      options:
        - Male
        - Female
  - type: dropdown
    id: license
    validations:
      required: true
    attributes:
      label: What license do you want to use / does the original source image use?
      description: |
        The most commonly used is CC-BY-SA, but CC0 is the least restrictive.

        If the image isn't yours, choose the license that the source image abides by.

        The following options are:
        - Public Domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).
        - Attribution Required ([CC BY](https://creativecommons.org/licenses/by/4.0/)).
        - Attribution + Share-Alike ([CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/))
        - Attribution + No-Derivatives ([CC BY-ND](https://creativecommons.org/licenses/by-nd/4.0/))
        - Attribution + Non-Commercial ([CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/))
        - Attribution + Non-Commercial + Share-Alike ([CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/))
        - Attribution + Non-Commercial + No-Derivatives ([CC BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/))
      options:
        - Public Domain (CC0)
        - Attribution Required (CC BY)
        - Attribution + Share-Alike (CC BY-SA)
        - Attribution + No-Derivatives (CC BY-ND)
        - Attribution + Non-Commercial (CC BY-NC)
        - Attribution + Non-Commercial + Share-Alike (CC BY-NC-SA)
        - Attribution + Non-Commercial + No-Derivatives (CC BY-NC-ND)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LeoDog896/ferret_images/blob/main/CODE_OF_CONDUCT.md) and the license you chose above.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I agree to license my image Creative Commons license above, or if the image isn't mine, that I have checked that the image is licensed under what I have chosen above..
          required: true